# Train

In [8]:
fig, ax = plt.subplots()

FigureCanvasNbAgg()

In [9]:
model = build_model()
trained_model = build_model()
trained_model.set_weights(model.get_weights())
#model.summary()

In [337]:
trained_model.set_weights(model.get_weights())

In [340]:
reset_samples()
eval_scores = [eval(trained_model, eval_cache_input, eval_cache_output)]
all_eval_scores = eval_scores[:]


In [102]:
reset_samples()

In [341]:
for i in range(20):  
    mcts_generate()
    clear_output()
    
    p = np.random.permutation(int(number_of_samples))
    if len(p) > BATCH_SIZE * TRAINING_LOOPS:
        p = p[:BATCH_SIZE * TRAINING_LOOPS]
    train_outputs = []
    train_inputs = []
    for i in range(len(sample_outputs)):
        train_outputs.append(sample_outputs[i][p])
    for i in range(len(sample_inputs)):
        train_inputs.append(sample_inputs[i][p])
        
    trained_model.fit(train_inputs, train_outputs, epochs=1, batch_size=BATCH_SIZE)    
    
    eval_new = eval(trained_model, eval_cache_input, eval_cache_output)
    if eval_new > eval_scores[-1]:
        eval_scores.append(eval_new)
        print("New model score: " + str(eval_scores[-1]) + "!")
        model.set_weights(trained_model.get_weights())
    print("Last scores: " + str(eval_scores[::-1]) + "!")
    all_eval_scores.append(eval_new)
    
plt.plot(all_eval_scores, label='6x75')
ax.legend(shadow=True)
plt.show()

Epoch 1/1
5626/5626 [==============================] - 0s 34us/step - loss: 0.0658 - dense_28_loss: 5.4652e-04 - dense_32_loss: 0.0652 - dense_28_acc: 0.8763 - dense_32_acc: 0.3797


  0%|          | 0/375 [00:00<?, ?it/s]

Last scores: [0.83]!


 14%|█▍        | 54/375 [00:32<03:49,  1.40it/s]


KeyboardInterrupt: 

In [371]:
sample_outputs[0][57]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.01786616, 0.        , 0.        , 0.82487374,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.11344697, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.04381313])

In [370]:
sample_inputs[0][57]

array([[[0, 0],
        [1, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 1],
        [0, 0],
        [0, 0],
        [0, 0],
        [1, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [1, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[1, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

In [48]:
model.predict_single([train_inputs[0][next_index - 2], train_inputs[1][next_index - 2]])

[array([0.00457216, 0.00180318, 0.01577809, 0.0150674 , 0.01713278,
        0.02392219, 0.00085306, 0.00843999, 0.0131199 , 0.00834722,
        0.01267777, 0.00257552, 0.01471896, 0.00836668, 0.00711771,
        0.00428187, 0.00709269, 0.00517327, 0.00248683, 0.00125713,
        0.00509079, 0.00299105, 0.0019958 , 0.00897587, 0.00642106,
        0.00954094, 0.003382  , 0.00594872, 0.00948039, 0.00568606,
        0.00555057, 0.00598032], dtype=float32),
 array([-0.6679595], dtype=float32)]

In [45]:
train_outputs[0][next_index - 2]

array([0.258651  , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.27687292, 0.        , 0.        , 0.        ,
       0.46447608, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [46]:
train_inputs[0][next_index - 2]

array([[[0, 1],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [1, 0]],

       [[1, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [1, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

In [116]:
model.set_weights(trained_model.get_weights())

In [104]:
for i in range(3):
    trained_model.fit(sample_inputs, sample_outputs, epochs=1, batch_size=BATCH_SIZE)  
    print(eval(trained_model, eval_cache_input, eval_cache_output))

Epoch 1/1
239616/300000 [======================>.......] - ETA: 1s - loss: 0.0043 - dense_28_loss: 5.3288e-04 - dense_32_loss: 0.0038 - dense_28_acc: 0.0065 - dense_32_acc: 0.9959

KeyboardInterrupt: 

In [333]:
eval(trained_model, eval_cache_input, eval_cache_output)

0.83

In [61]:
model_output = model.predict([sample_inputs[0], sample_inputs[1]])[0]
a = np.argmax(model_output, axis=-1)
k = np.equal(np.take(sample_outputs[0], np.argmax(sample_outputs[0], axis=-1)), np.take(sample_outputs[0], a)).sum()
k / len(sample_outputs[0])

0.9862666666666666

In [53]:
model.save('model.h5')

In [10]:
model.load_weights('modelDense.h5')

In [62]:
compare(model, None)

0.35

In [59]:
match([model, None])

1