# Train

In [270]:
fig, ax = plt.subplots()

/usr/local/lib/python3.6/dist-packages/matplotlib/pyplot.py:528: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)


FigureCanvasNbAgg()

In [393]:
model = build_model()
trained_model = build_model()
#trained_model.set_weights(model.get_weights())
#model.summary()

In [394]:
reset_samples()
eval_scores = [eval(trained_model, eval_games)]
all_eval_scores = eval_scores[:]


In [405]:
from IPython.display import clear_output
for i in range(1):  
    reset_samples()
    mcts_generate()
    clear_output()
    
    #p = np.random.permutation(int(number_of_samples))
    #if len(p) > BATCH_SIZE * TRAINING_LOOPS:
    #    p = p[:BATCH_SIZE * TRAINING_LOOPS]
    #train_outputs = []
    #train_inputs = []
   #for i in range(len(sample_outputs)):
    #    train_outputs.append(sample_outputs[i][p])
    #for i in range(len(sample_inputs)):
    #    train_inputs.append(sample_inputs[i][p])
        
    #trained_model.fit(train_inputs, train_outputs, epochs=1, batch_size=BATCH_SIZE)    
    
    eval_new = eval(model, eval_games)
    if eval_new > eval_scores[-1]:
        eval_scores.append(eval_new)
    print("Model score: " + str(eval_new) + "!")
       # model.set_weights(trained_model.get_weights())
    print("Last scores: " + str(eval_scores[::-1]) + "!")
    all_eval_scores.append(eval_new)
    
plt.plot(all_eval_scores, label='6x75')
ax.legend(shadow=True)
plt.show()

Model score: 0.7157738095238099!
Last scores: [0.7410714285714289, 0.7291666666666667, 0.7008928571428571, 0.6979166666666666, 0.6934523809523814, 0.6889880952380951, 0.6875000000000002, 0.6845238095238099, 0.6651785714285715, 0.6607142857142856, 0.6592261904761906, 0.6532738095238094, 0.6160714285714282, 0.6116071428571427, 0.5892857142857142, 0.5848214285714287, 0.5669642857142858, 0.505952380952381, 0.39434523809523825, 0.300595238095238, 0.0]!


In [412]:
eval(model, eval_games)

0.7113095238095241

In [397]:
sample_inputs[0][7]

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [1, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [1, 0],
        [0, 0],
        [0, 0],
        [0, 1]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

In [93]:
compare(model, trained_model)

0.506

In [48]:
model.predict_single([train_inputs[0][next_index - 2], train_inputs[1][next_index - 2]])

[array([0.00457216, 0.00180318, 0.01577809, 0.0150674 , 0.01713278,
        0.02392219, 0.00085306, 0.00843999, 0.0131199 , 0.00834722,
        0.01267777, 0.00257552, 0.01471896, 0.00836668, 0.00711771,
        0.00428187, 0.00709269, 0.00517327, 0.00248683, 0.00125713,
        0.00509079, 0.00299105, 0.0019958 , 0.00897587, 0.00642106,
        0.00954094, 0.003382  , 0.00594872, 0.00948039, 0.00568606,
        0.00555057, 0.00598032], dtype=float32),
 array([-0.6679595], dtype=float32)]

In [45]:
train_outputs[0][next_index - 2]

array([0.258651  , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.27687292, 0.        , 0.        , 0.        ,
       0.46447608, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [46]:
train_inputs[0][next_index - 2]

array([[[0, 1],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [1, 0]],

       [[1, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [1, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

In [111]:
test_model = build_model()

In [72]:
K.set_value(test_model.optimizer.lr, 0.0001)

In [132]:
test_model.fit([sample_inputs[0][:number_of_samples], sample_inputs[1][:number_of_samples]], [sample_outputs[0][:number_of_samples], sample_outputs[1][:number_of_samples]], epochs=10, batch_size=BATCH_SIZE)  

Epoch 1/10
37764/37764 [==============================] - 1s 27us/step - loss: 0.6618 - dense_14_loss: 2.8052e-04 - dense_15_loss: 0.6615 - dense_14_acc: 0.5164 - dense_15_acc: 0.4518
Epoch 2/10
37764/37764 [==============================] - 1s 24us/step - loss: 0.6619 - dense_14_loss: 2.7928e-04 - dense_15_loss: 0.6616 - dense_14_acc: 0.5180 - dense_15_acc: 0.4519
Epoch 3/10
37764/37764 [==============================] - 1s 24us/step - loss: 0.6618 - dense_14_loss: 2.7612e-04 - dense_15_loss: 0.6616 - dense_14_acc: 0.5203 - dense_15_acc: 0.4518
Epoch 4/10
37764/37764 [==============================] - 1s 24us/step - loss: 0.6618 - dense_14_loss: 2.7579e-04 - dense_15_loss: 0.6615 - dense_14_acc: 0.5171 - dense_15_acc: 0.4513
Epoch 5/10
37764/37764 [==============================] - 1s 25us/step - loss: 0.6618 - dense_14_loss: 2.7352e-04 - dense_15_loss: 0.6615 - dense_14_acc: 0.5153 - dense_15_acc: 0.4513
Epoch 6/10
37764/37764 [==============================] - 1s 26us/step - loss: 0

In [116]:
test_model.predict_single([sample_inputs[0][5], sample_inputs[1][5]])

[array([0.0053017 , 0.0045248 , 0.00548624, 0.00582314, 0.0070843 ,
        0.00583717, 0.00645116, 0.00290738, 0.00513383, 0.0056636 ,
        0.331735  , 0.00607965, 0.0053452 , 0.00601907, 0.33392397,
        0.0070668 , 0.00368037, 0.01111693, 0.00290891, 0.00334794,
        0.00270144, 0.00335149, 0.00295761, 0.00356095, 0.00431994,
        0.00539099, 0.00628497, 0.00557014, 0.3452927 , 0.00649954,
        0.00652416, 0.00288056], dtype=float32),
 array([-0.81022185], dtype=float32)]

In [110]:
sample_outputs[0][10]

37764

In [152]:
sample_outputs[0][10638]

array([0.        , 0.23038077, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.15442885, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.23038077,
       0.        , 0.        , 0.        , 0.23038077, 0.        ,
       0.        , 0.        , 0.        , 0.15442885, 0.        ,
       0.        , 0.        ])

In [97]:
eval(model, eval_cache_input, eval_cache_output)

0.127

In [133]:
model_output = test_model.predict([sample_inputs[0][:number_of_samples], sample_inputs[1][:number_of_samples]])[0]
a = np.argmax(model_output, axis=-1)
k = np.equal(np.take(sample_outputs[0][:number_of_samples], np.argmax(sample_outputs[0][:number_of_samples], axis=-1)), np.take(sample_outputs[0][:number_of_samples], a)).sum()
k / number_of_samples

0.8743247537337147

In [252]:
model.save('modelDense2.h5')

In [82]:
model.load_weights('modelDense2.h5')

In [228]:
compare(model, first_model)

0.5128

In [59]:
match([model, None])

1

In [125]:
first_model = model