# Train

In [236]:
fig, ax = plt.subplots()

/usr/local/lib/python3.6/dist-packages/matplotlib/pyplot.py:528: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)


FigureCanvasNbAgg()

In [231]:
model = build_model()
trained_model = build_model()
trained_model.set_weights(model.get_weights())
#model.summary()

In [254]:
trained_model.set_weights(model.get_weights())

In [232]:
reset_samples()
eval_scores = [eval(trained_model, eval_cache_input, eval_cache_output)]
all_eval_scores = eval_scores[:]


0 0.0 0.12
1 0.0 0.07
2 0.0 0.59
3 0.0 0.59
4 0.0 0.41
6 0.0 0.39
7 0.0 0.95
8 0.0 0.07
9 0.26 0.77
10 0.0 0.67
11 0.0 0.98
12 0.0 0.76
13 0.0 0.57
14 0.0 0.39
15 0.0 0.9
16 0.0 0.96
17 0.0 1.0
18 0.0 0.75
19 0.0 1.0
20 0.0 0.11
23 0.0 1.0
24 0.0 0.58
26 0.0 0.69
27 0.0 0.4
28 0.0 0.44
29 0.0 1.0
30 0.0 0.83
31 0.0 0.16
32 0.0 0.86
33 0.0 0.33
35 0.0 0.77
36 0.0 1.0
37 0.0 0.92
38 0.0 0.87
39 0.0 0.06
40 0.0 0.44
41 0.0 0.69
43 0.0 1.0
44 0.0 0.54
45 0.0 1.0
46 0.0 0.24
47 0.0 1.0
48 0.0 0.15
49 0.0 0.63
50 0.0 0.12
51 0.0 1.0
52 0.0 0.09
54 0.0 0.38
56 0.0 1.0
57 0.0 0.85
58 0.0 0.93
59 0.0 0.25
60 0.98 1.0
61 0.0 0.32
62 0.0 0.33
63 0.0 0.3
64 0.0 1.0
65 0.0 0.42
66 0.0 0.13
68 0.0 0.66
69 0.0 0.31
70 0.0 0.38
71 0.0 0.36
72 0.0 0.18
74 0.0 1.0
75 0.0 0.55
77 0.0 0.99
78 0.0 0.95
79 0.0 0.19
80 0.0 0.37
81 0.0 0.71
82 0.69 0.81
83 0.0 1.0
84 0.0 0.18
87 0.0 0.9
88 0.0 0.93
89 0.0 0.97
90 0.0 0.97
91 0.0 0.98
92 0.0 0.45
93 0.0 0.48
94 0.0 0.82
95 0.0 0.87
96 0.3 0.69
97 0.0 0.02
98 0

In [248]:
reset_samples()

In [260]:
for i in range(100):  
    mcts_generate()
    clear_output()
    
    p = np.random.permutation(int(number_of_samples))
    if len(p) > BATCH_SIZE * TRAINING_LOOPS:
        p = p[:BATCH_SIZE * TRAINING_LOOPS]
    train_outputs = []
    train_inputs = []
    for i in range(len(sample_outputs)):
        train_outputs.append(sample_outputs[i][p])
    for i in range(len(sample_inputs)):
        train_inputs.append(sample_inputs[i][p])
        
    trained_model.fit(train_inputs, train_outputs, epochs=1, batch_size=BATCH_SIZE)    
    
    eval_new = eval(trained_model, eval_cache_input, eval_cache_output)
    if eval_new > eval_scores[-1]:
        eval_scores.append(eval_new)
        print("New model score: " + str(eval_scores[-1]) + "!")
        model.set_weights(trained_model.get_weights())
    print("Last scores: " + str(eval_scores[::-1]) + "!")
    all_eval_scores.append(eval_new)
    
plt.plot(all_eval_scores, label='6x75')
ax.legend(shadow=True)
plt.show()

Epoch 1/1
19712/25600 [======================>.......] - ETA: 0s - loss: 0.0773 - dense_76_loss: 2.0104e-04 - dense_80_loss: 0.0771 - dense_76_acc: 0.6166 - dense_80_acc: 0.4655

KeyboardInterrupt: 

In [251]:
all_eval_scores

[0.14,
 0.1,
 0.11,
 0.14,
 0.14,
 0.14,
 0.15,
 0.13,
 0.16,
 0.17,
 0.17,
 0.17,
 0.17,
 0.16,
 0.15,
 0.16,
 0.16,
 0.09,
 0.08,
 0.19,
 0.17,
 0.3,
 0.35,
 0.39,
 0.51,
 0.54,
 0.57,
 0.61,
 0.65,
 0.69,
 0.68,
 0.67,
 0.68,
 0.66,
 0.67,
 0.66,
 0.7,
 0.73,
 0.74,
 0.75,
 0.78,
 0.73,
 0.72,
 0.75,
 0.77,
 0.78,
 0.76,
 0.74,
 0.73,
 0.76,
 0.81,
 0.78,
 0.71,
 0.75,
 0.74,
 0.76,
 0.76,
 0.76,
 0.77,
 0.8,
 0.8,
 0.76,
 0.76,
 0.76,
 0.84,
 0.77,
 0.83,
 0.77,
 0.77,
 0.75,
 0.76,
 0.78,
 0.74,
 0.79,
 0.78,
 0.78,
 0.81,
 0.8,
 0.81,
 0.78,
 0.81,
 0.83,
 0.79,
 0.81,
 0.81,
 0.79,
 0.79,
 0.78,
 0.78,
 0.82,
 0.8,
 0.78,
 0.82,
 0.81,
 0.82,
 0.8,
 0.82,
 0.84,
 0.81,
 0.82,
 0.8,
 0.83,
 0.82,
 0.83,
 0.83,
 0.83,
 0.83,
 0.83,
 0.85,
 0.84,
 0.86,
 0.82,
 0.88,
 0.82,
 0.88,
 0.86,
 0.88,
 0.89,
 0.87,
 0.88,
 0.85,
 0.9,
 0.85,
 0.84,
 0.93,
 0.85,
 0.87,
 0.85,
 0.82]

In [370]:
sample_inputs[0][57]

array([[[0, 0],
        [1, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 1],
        [0, 0],
        [0, 0],
        [0, 0],
        [1, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [1, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[1, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

In [48]:
model.predict_single([train_inputs[0][next_index - 2], train_inputs[1][next_index - 2]])

[array([0.00457216, 0.00180318, 0.01577809, 0.0150674 , 0.01713278,
        0.02392219, 0.00085306, 0.00843999, 0.0131199 , 0.00834722,
        0.01267777, 0.00257552, 0.01471896, 0.00836668, 0.00711771,
        0.00428187, 0.00709269, 0.00517327, 0.00248683, 0.00125713,
        0.00509079, 0.00299105, 0.0019958 , 0.00897587, 0.00642106,
        0.00954094, 0.003382  , 0.00594872, 0.00948039, 0.00568606,
        0.00555057, 0.00598032], dtype=float32),
 array([-0.6679595], dtype=float32)]

In [45]:
train_outputs[0][next_index - 2]

array([0.258651  , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.27687292, 0.        , 0.        , 0.        ,
       0.46447608, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [46]:
train_inputs[0][next_index - 2]

array([[[0, 1],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [1, 0]],

       [[1, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [1, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

In [116]:
model.set_weights(trained_model.get_weights())

In [253]:
for i in range(3):
    trained_model.fit(sample_inputs, sample_outputs, epochs=1, batch_size=BATCH_SIZE)  
    print(eval(trained_model, eval_cache_input, eval_cache_output))

Epoch 1/1
300000/300000 [==============================] - 9s 31us/step - loss: 0.0034 - dense_76_loss: 6.1776e-04 - dense_80_loss: 0.0028 - dense_76_acc: 0.0108 - dense_80_acc: 0.9770
0 0.0 0.12
1 0.0 0.07
2 0.0 0.59
4 0.0 0.41
10 0.58 0.67
14 0.21 0.39
15 0.0 0.9
16 0.71 0.96
17 0.0 1.0
18 0.65 0.75
19 0.65 1.0
21 0.0 0.45
24 0.47 0.58
26 0.36 0.69
27 0.37 0.4
30 0.56 0.83
32 0.24 0.86
33 0.0 0.33
35 0.5 0.77
40 0.24 0.44
45 0.99 1.0
48 0.0 0.15
52 0.0 0.09
54 0.17 0.38
56 0.0 1.0
58 0.0 0.93
59 0.0 0.25
62 0.19 0.33
64 0.94 1.0
65 0.0 0.42
69 0.0 0.31
70 0.0 0.38
71 0.0 0.36
72 0.0 0.18
77 0.0 0.99
78 0.0 0.95
82 0.7 0.81
86 0.09 0.39
87 0.85 0.9
88 0.92 0.93
90 0.0 0.97
92 0.2 0.45
94 0.0 0.82
95 0.86 0.87
96 0.13 0.69
97 0.01 0.02
99 0.0 0.33
0.53
Epoch 1/1
300000/300000 [==============================] - 11s 36us/step - loss: 0.0032 - dense_76_loss: 5.6959e-04 - dense_80_loss: 0.0027 - dense_76_acc: 0.0106 - dense_80_acc: 0.9770
0 0.0 0.12
1 0.0 0.07
2 0.0 0.59
4 0.0 0.41
10 0.58

In [333]:
eval(trained_model, eval_cache_input, eval_cache_output)

0.83

In [61]:
model_output = model.predict([sample_inputs[0], sample_inputs[1]])[0]
a = np.argmax(model_output, axis=-1)
k = np.equal(np.take(sample_outputs[0], np.argmax(sample_outputs[0], axis=-1)), np.take(sample_outputs[0], a)).sum()
k / len(sample_outputs[0])

0.9862666666666666

In [252]:
model.save('modelDense2.h5')

In [16]:
model.load_weights('modelDense.h5')

In [62]:
compare(model, None)

0.35

In [59]:
match([model, None])

1